environments:
  - type: 1
    awsAccounts:
     - 1eng
     - 1test
     - 1prod
     - 1loc
     - 2loc
     - ess-Prod-preview
     - ess-Prod-live
     - fis-Prod-preview
     - fis-Prod-live


  
