name: AEM Deployment

on:
  push:
    branches: [ main ]  # Adjust the branch to trigger the deployment

jobs:
  deploy:
    runs-on: aem  # Adjust the runner OS if needed
    steps:
      #- uses: actions/checkout@v3  # Checkout your repository code

      - name: Download AEM package (optional)
        # Uncomment if your package isn't already in the repository:
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AEM_PACKAGE_NAME }}
          path: .

      - name: Upload AEM package
        run: |
          curl -u ${{ secrets.AEM_CREDENTIALS }} \
            -F cmd=upload \
            -F force=true \
            -F package=@${{ env.AEM_PACKAGE_NAME }} \
            http://${{ secrets.AEM_HOST }}:4502/crx/packmgr/service/.json
        env:
          AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
          AEM_HOST: ${{ secrets.AEM_HOST }}
          AEM_PACKAGE_NAME: "we.retail.community.apps-1.11.84.zip" 

