name: AEM Deployment Workflow

on:
  push:
    branches: [ main ]

jobs:
  Get-Package:
    runs-on: aem  # Adjust the runner OS if needed
    steps:
      # ... existing steps for downloading git ...

  Upload-Package:
    runs-on: aem  # Adjust the runner OS if needed
    steps:
      - name: Checkout code (if needed)
        uses: actions/checkout@v3

      - name: Get server address
        run: |
          echo "Select server environment (dev, stage, or prod):"
          read server_address

          if [[ "$server_address" == "dev" ]]; then
            aem_host=${{ env.AEM_DEV_HOST }}
          elif [[ "$server_address" == "stage" ]]; then
            aem_host=${{ env.AEM_STAGE_HOST }}
          else
            echo "Invalid server address!"
            exit 1
          fi

      - name: Upload AEM package (conditional)
        run: |
          curl -u ${{ secrets.AEM_CREDENTIALS }} \
            -F cmd=upload \
            -F force=true \
            -F package=@${{ env.AEM_PACKAGE_NAME }} \
            http://$aem_host:4502/crx/packmgr/service/.json
