name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: '1loc'
        options:
          - 1eng
          - 1test
          - 1prod
          - 1loc

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Common Repository Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: your-username/Common
          event-type: deploy-environment
          client-payload: '{"environment": "${{ github.event.inputs.environment }}"}'
