# This line defines the workflow name (displayed in GitHub Actions UI)
name: My Basic Workflow

# This section defines when the workflow will be triggered. Here, it runs on push events.
# You can use other events like pull_request or schedule (for cron jobs)
on: push
  

# This section defines the jobs within the workflow. A job can have multiple steps.
jobs:
  build:  # Name of the job (displayed in GitHub Actions UI)
    runs-on: ubuntu-latest  # This defines the runner OS (e.g., ubuntu-latest, macos-monterey)

    # This section defines the steps within the job. Each step executes a command.
    steps:
      - uses: actions/checkout@v3  # This pre-defined action checks out the repository code
        with:
          # This defines additional options for the action (optional)
          fetch-depth: 0  # Fetches all commits from history (optional)

      - name: Install dependencies  # Descriptive name for the step (optional)
        run: date

      - name: Run tests  # Descriptive name for the step (optional)
        run: uname -r
