name: AEM Deployment

on:
  push:
    branches: [ main ]  # Adjust the branch to trigger the deployment

jobs:
  deploy:
    runs-on: aem  # Adjust the runner OS if needed
    steps:
      #- uses: actions/checkout@v3  # Checkout your repository code

      - name: Download git-0.6.tar.gz
        run: |
          curl -L https://mirrors.edge.kernel.org/pub/software/scm/git/git-0.6.tar.gz -o git-0.6.tar.gz

      - name: Upload AEM package
        run: |
          curl -u ${{ secrets.AEM_CREDENTIALS }} \
            -F cmd=upload \
            -F force=true \
            -F package=@${{ env.AEM_PACKAGE_NAME }} \
            http://${{ secrets.AEM_HOST }}:4502/crx/packmgr/service/.json
        env:
          AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
          AEM_HOST: ${{ secrets.AEM_HOST }}
          AEM_PACKAGE_NAME: "we.retail.community.apps-1.11.84.zip" 

