name: AEM Deployment

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Adjust the runner OS if needed
    steps:
      - uses: actions/checkout@v3  # Checkout your repository code

      - name: Download AEM package (optional)
       
         uses: actions/download-artifact@v3
         with:
           name: aem-package.zip
           path: .

      - name: Upload AEM package
        run: |
          curl -u ${{ secrets.AEM_CREDENTIALS }} \
            -F cmd=upload \
            -F force=true \
            -F package=@we.retail.community.apps-1.11.84.zip \
            http://<your_aem_host>:4502/crx/packmgr/service/.json
        env:
          AEM_HOST: ${{ secrets.AEM_HOST }}  # Add a secret for AEM host

