name: Extract Values and Use Variables 

on:
  push:
    branches:
      - main11

jobs:
  extract-values:
    runs-on: rhel88

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload AEM package (conditional)
      env:
        AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
        AEM_PACKAGE_NAME: "we.retail.community.apps-1.11.84.zip"
        AEM_HOST: ${{ secrets.AEM_HOST }}
      run: |
        response=$(curl -u $AEM_CREDENTIALS \
          -F cmd=upload \
          -F force=true \
          -F package=@$AEM_PACKAGE_NAME \
          http://$AEM_HOST:4502/crx/packmgr/service/.json)
        echo "$response" > response.json
    - name: Extract values from response
      id: extract
      run: |
        group=$(jq -r '.data.package.group' response.json)
        downloadName=$(jq -r '.data.package.downloadName' response.json)
        echo "group=$group" >> $GITHUB_ENV
        echo "downloadName=$downloadName" >> $GITHUB_ENV
    - name: Print extracted values
      run: |
        echo "Group: ${{ env.group }}"
        echo "Download Name: ${{ env.downloadName }}"
    # Add subsequent steps here that use the extracted values
    - name: Use extracted values
      run: |
        # Example of using the extracted values
        echo "Using group: ${{ env.group }}"
        echo "Using downloadName: ${{ env.downloadName }}"
