name: Extract Values and Use Variables 

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  extract-values:
    runs-on: self-hosted
    runs-on: redhat01
    needs: checkout

    steps:
    - name: Checkout code (again)
      uses: actions/checkout@v2

    - name: Verify AEM package exists
      run: |
        if [ ! -f we.retail.community.apps-1.11.84.zip ]; then
          echo "AEM package not found!"
          exit 1
        fi

    - name: Upload AEM package (conditional)
      env:
        AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
        AEM_PACKAGE_NAME: "we.retail.community.apps-1.11.84.zip"
        AEM_HOST: ${{ secrets.AEM_HOST }}
      run: |
        response=$(curl -u $AEM_CREDENTIALS \
          -F cmd=upload \
          -F force=true \
          -F package=@${{ env.AEM_PACKAGE_NAME }} \
          http://$AEM_HOST:4502/crx/packmgr/service/.json)
        echo "$response" > response.json

    - name: Extract values from response
      id: extract
      run: |
        group=$(jq -r '.data.package.group' response.json)
        downloadName=$(jq -r '.data.package.downloadName' response.json)
        echo "group=$group" >> $GITHUB_ENV
        echo "downloadName=$downloadName" >> $GITHUB_ENV

    - name: Print extracted values
      run: |
        echo "Group: ${{ env.group }}"
        echo "Download Name: ${{ env.downloadName }}"

    - name: Use extracted values
      run: |
        echo "Using group: ${{ env.group }}"
        echo "Using downloadName: ${{ env.downloadName }}"
